package Views;

import javax.swing.JOptionPane;
import Controller.CadastroBD;
import Model.Usuarios;

/**
 *
 * @author aluno
 */
public class Cadastrar extends javax.swing.JFrame {
    private String nome,cpf,telefone,email,cidade,rua,senha,cep,n,uf;
    private Login hm;
    public Cadastrar() {
        initComponents();
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btHome = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        campoRua = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        campoTel = new javax.swing.JTextField();
        campoEmailCad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        campoCEP = new javax.swing.JTextField();
        campoN = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        campoUF = new javax.swing.JTextField();
        campoSenhaCad = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar");
        setLocation(new java.awt.Point(350, 125));
        setPreferredSize(new java.awt.Dimension(800, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 555));
        jPanel1.setMinimumSize(new java.awt.Dimension(903, 555));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btHome.setText("VOLTAR");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        btHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btHomeKeyPressed(evt);
            }
        });
        jPanel1.add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 109, -1));

        campoNome.setBackground(new java.awt.Color(237, 237, 237));
        campoNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoNome.setBorder(null);
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 620, 10));

        campoRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRuaActionPerformed(evt);
            }
        });
        jPanel1.add(campoRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, -1));

        campoCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(campoCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 180, -1));

        campoTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(campoTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 130, -1));

        campoEmailCad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(campoEmailCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 396, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("c");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));
        jPanel1.add(campoCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 117, -1));
        jPanel1.add(campoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 40, -1));
        jPanel1.add(campoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 150, 21));

        campoUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUFActionPerformed(evt);
            }
        });
        jPanel1.add(campoUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 60, -1));
        jPanel1.add(campoSenhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 161, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela Cadastrar.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuarios usuario = new Usuarios();
        CadastroBD CadastroBD = new CadastroBD();

        nome = campoNome.getText();
        cpf = campoCPF.getText();
        telefone = campoTel.getText();
        email = campoEmailCad.getText();
        cidade = campoCidade.getText();
        rua = campoRua.getText();
        senha = campoSenhaCad.getText();
        cep = campoCEP.getText();
        n = campoN.getText();
        uf = campoUF.getText();

        usuario.setNome(nome);
        usuario.setCpf(cpf);
        usuario.setTelefone(telefone);
        usuario.setEmail(email);
        usuario.setCidade(cidade);
        usuario.setRua(rua);
        usuario.setSenha(senha);
        usuario.setCep(cep);
        usuario.setN(n);
        usuario.setUf(uf);

        if(CadastroBD.inserirUsuarios(usuario) == true)
        {
            JOptionPane.showMessageDialog(null, "Você foi cadastrado com sucesso!!!", "Cadastro",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Erro no cadastro", "Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCidadeActionPerformed

    private void campoRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRuaActionPerformed

    private void btHomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btHomeKeyPressed

    }//GEN-LAST:event_btHomeKeyPressed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        hm = new Login();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHome;
    private javax.swing.JTextField campoCEP;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoEmailCad;
    private javax.swing.JTextField campoN;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoRua;
    private javax.swing.JPasswordField campoSenhaCad;
    private javax.swing.JTextField campoTel;
    private javax.swing.JTextField campoUF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
